# Generated by Django 3.1.5 on 2021-01-21 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Age')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Book Name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Added Date/Time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated Date/Time')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Stock')),
                ('genre', models.PositiveSmallIntegerField(choices=[(1, 'Fiction'), (2, 'Adventure'), (3, 'Fantasy'), (4, 'Poetry'), (5, 'Drama'), (6, 'Biography'), (7, 'Mystery')], default=1, verbose_name='Gender')),
                ('condition', models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Best'), (3, 'Good'), (4, 'Old')], default=1, verbose_name='Gender')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Sale'), (2, 'Change'), (3, 'Notsale'), (4, 'Hidden')], default=1, verbose_name='Gender')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.authormodel')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
